- hosts: linux
  become: yes

  tasks:
  - name: Install Zabbix RPM Repo RHEL 5
    yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/5/x86_64/zabbix-release-3.4-1.noarch.rpm
    when: 
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "5"

  - name: Install Zabbix RPM Repo RHEL 6
    yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/6/x86_64/zabbix-release-3.4-1.el6.noarch.rpm
    when: 
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "6"

  - name: Install Zabbix RPM Repo RHEL 7
    yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"

  - name: Install zabbix-agent
    yum: name=zabbix-agent state=latest

  - name: Copy Zabbix Configs
    copy: src=zabbix_agentd.conf-svcacct dest=/etc/zabbix/zabbix_agentd.conf
    copy: src=zabbix-agent dest=/etc/logrotate.d/zabbix-agent

  - name: Set Permissions for Service Account
    file: path={{ item }} owner=eitzbxcp group=eitzbxcp state=directory recurse=yes mode=0755
    with_items:
      - /var/run/zabbix
      - /var/log/zabbix

  - service:
      name: zabbix-agent
      enabled: yes
      state: restarted

  - name: Check zabbix-agent port is open
    wait_for:
      port: 10050
      connect_timeout: 5
