---
  - name: Check if Port is Open to {{ west.zabbix.server }}
    wait_for:
      host: "{{ west.zabbix.server }}"
      port: 10051
      connect_timeout: 5
      timeout: 5

  - name: Install Zabbix RPM Repo RHEL 5
    retries: 3
    delay: 5
    yum:
      name: https://repo.zabbix.com/zabbix/3.4/rhel/5/x86_64/zabbix-release-3.4-1.noarch.rpm
      validate_certs: false
    when: 
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "5"

  - name: Install Zabbix RPM Repo RHEL 6
    retries: 3
    delay: 5
    yum:
      name: https://repo.zabbix.com/zabbix/3.4/rhel/6/x86_64/zabbix-release-3.4-1.el6.noarch.rpm
      validate_certs: false
    when: 
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "6"

  - name: Install Zabbix RPM Repo RHEL 7
    retries: 3
    delay: 5
    yum:
      name: https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
      validate_certs: false
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"

  - name: Install zabbix-agent
    retries: 3
    delay: 5
    yum:
      name: zabbix-agent
      state: latest
      validate_certs: false

  - name: Copy Zabbix Configs
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - { src: 'etc/zabbix/zabbix_agentd.conf.j2', dest: '/etc/zabbix/zabbix_agentd.conf' }
      - { src: 'etc/logrotate.d/zabbix-agent.j2', dest: '/etc/logrotate.d/zabbix-agent' }

  # opens permissions on /var/run/zabbix so both zabbix and eitzbxcp can write to it on reboot
  # needed since systemd-tmpfiles only checks /etc/passwd and /etc/group for user infomation
  - name: Copy Zabbix Configs RHEL 7
    template:
      src: usr/lib/tmpfiles.d/zabbix-agent.conf.j2
      dest: /usr/lib/tmpfiles.d/zabbix-agent.conf
      owner: root
      group: root
      mode: 0644
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"

  - name: Set Permissions for Service Account
    file: 
      path: "{{ item }}"
      owner: "{{ west.zabbix.owner }}"
      group: "{{ west.zabbix.group }}"
      state: directory 
      mode: 0755 
      recurse: yes
    with_items:
      - /var/run/zabbix
      - /var/log/zabbix

  - name: Open Local Firewall Port for Saved and Running Config
    firewalld:
      port: "{{ item.port }}"
      permanent: "{{ item.perm }}"
      zone: public
      state: enabled
    with_items:
      - { port: '10050/tcp', perm: 'true' }
      - { port: '10050/tcp', perm: 'false' }
    notify:
      - Reload Firewalld
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"

  - name: Enable and start the Zabbix agent
    service:
      name: zabbix-agent
      enabled: yes
      state: restarted

  - name: Check zabbix-agent Port is Open Locally
    wait_for:
      port: 10050
      connect_timeout: 5
      timeout: 5

...
