---
# the setup_monitoring role is the same as the one used in the ETS-prep playbook
# except uses the set_properties.yml file to override the defaults instead of the 
# datacenter variable files.

- hosts: linux
  become: yes

  pre_tasks:

  - name: Include Properties File for Server FQDNs and User Info
    include_vars:
      file: properties.yml

  - name: Set Zabbix Default Values
    include_vars:
      file: defaults.yml
      name: west

  - name: Set Zabbix Property Variables
    include: set_properties.yml

  roles: 
    - { role: setup_monitoring, tags: [setup_monitoring] }

...
